services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: runbuddy-server:latest
    env_file:
      - server/.env # optional
    ports:
      - "8000:8000"
    # Dev hot reload:
    volumes:
      - ./server:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: runbuddy-client:latest
    ports:
      - "3000:3000"
    env_file:
    - client/.env
    volumes:
      - ./client:/app # Hot reload sync with local edits
      - /app/node_modules # Avoid overwriting node_modules
    depends_on:
      - server
    restart: unless-stopped
